export const GET_ALL_SCORING = "GET_ALL_SCORING"
export const SET_ALL_SCORING = "SET_ALL_SCORING"
export const CREATE_SCORING = "CREATE_SCORING"
export const UPDATE_SCORING = "UPDATE_SCORING"
export const DELETE_SCORING = "DELETE_SCORING"
export const GET_SCORING_DETAIL = "GET_SCORING_DETAIL"
export const SET_SCORING_DETAIL = "SET_SCORING_DETAIL"

