export const GET_ALL_LICENSES = "GET_ALL_LICENSES"
export const SET_ALL_LICENSES = "SET_ALL_LICENSES"
export const GET_LICENSE_DETAIL = "GET_LICENSE_DETAIL"
export const SET_LICENSE_DETAIL = "SET_LICENSE_DETAIL"
export const CREATE_LICENSE = "CREATE_LICENSE"
export const UPDATE_LICENSE = "UPDATE_LICENSE"
export const DELETE_LICENSE = "DELETE_LICENSE"

