export const GET_UPCOMING_EVENTS = "GET_UPCOMING_EVENTS"
export const SET_UPCOMING_EVENTS = "SET_UPCOMING_EVENTS"
export const GET_ACTIVE_SERIES = "GET_ACTIVE_SERIES"
export const SET_ACTIVE_SERIES = "SET_ACTIVE_SERIES"
